### ISSUE TITLE
pkg-config fails for libsegwayrmp system package

### ISSUE THREAD

**Issue by piyushk** [segwayrmp/libsegwayrmp#5]
I've begun work on https://github.com/segwayrmp/segway-rmp-ros-pkg/pull/9 + catkinizing and releasing segway-rmp-ros-pkg.

pkg-config is unaware of libsegwayrmp as no pc file exists for this package. I still have not ramped up on catkin/bloom, so I am not currently sure what the error is. I do see that libsegwayrmp does not seem to be using catkin, and seems to be building directly against cmake.

Here is the output of make inside segway_rmpX

```
piyushk@bwi-ens-1:~/ros/rosbuild_ws/segway_rmp/segway_rmpX$ make
mkdir -p bin
cd build && cmake -Wdev -DCMAKE_TOOLCHAIN_FILE=/opt/ros/groovy/share/ros/core/rosbuild/rostoolchain.cmake  ..
[rosbuild] Building package segway_rmpX
[rosbuild] Cached build flags older than manifests; calling rospack to get flags
Failed to invoke /opt/ros/groovy/bin/rospack cflags-only-I;--deps-only segway_rmpX
Package libsegwayrmp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsegwayrmp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsegwayrmp' found
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rosdep2/rospack.py", line 45, in call_pkg_config
    value = subprocess.check_output(['pkg-config', option, pkg_name])
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pkg-config', '--cflags-only-I', 'libsegwayrmp']' returned non-zero exit status 1
[rospack] Error: could not call python function 'rosdep2.rospack.call_pkg_config'


CMake Error at /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:129 (message):


  Failed to invoke rospack to get compile flags for package 'segway_rmpX'.
  Look above for errors from rospack itself.  Aborting.  Please fix the
  broken dependency!

Call Stack (most recent call first):
  /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:227 (rosbuild_invoke_rospack)
  CMakeLists.txt:12 (rosbuild_init)


-- Configuring incomplete, errors occurred!
make: *** [all] Error 1
```

If you have any obvious suggestions regarding this, let me know. I will probably continue work on this on the weekend.

**Comment by piyushk** [comment]
Hmm. I had trouble even getting libsegwayrmp to compile locally. Opened upstream bug: https://github.com/ros/catkin/issues/340

**Comment by piyushk** [comment]
This issue has been resolved as user error. See http://answers.ros.org/question/61623/do-plain-cmake-packages-need-to-handle-pkg-config-file-generation/ for solution.
